version: '2'
services:

  app1:
    build: ./app1
    restart: always

  app2:
    build: ./app2
    restart: always

  nginx:
    image: nginx:1.10
    ports:
      - '8100:80'
    restart: always
    depends_on:
      - app1
      - app2
